extends "res://tools/test_world3d_buildings.gd"
const Fort=preload("res://scripts/world3d/fortification_data.gd")
const Plan=preload("res://scripts/world3d/fortification_plan.gd")
const Layout=preload("res://scripts/world3d/city_layout.gd")
const Frozen=preload("res://scripts/world3d/house_prefab.gd")
func run()->void:
	create_timer(300).timeout.connect(func():quit(2))
	var directory:=Paths.cache_directory("structure_prefab_test_%d"%Time.get_ticks_usec());var path:=directory.path_join("map.gltf")
	var doc:=Doc.new();doc.add_box("ground",Vector3(0,-.2,0),Vector3(180,.4,140))
	var settings:=Fort.defaults().merged({"id":"legacy_wall","points":[[-24,-30],[24,-30]],"style":"plain","closed":false,"corner_towers":false,"wall_access":false,"arrow_slits":false,"gates":[{"id":"gate","segment":0,"t":.5,"width":6.0,"height":5.0,"open":.7}]},true)
	var plan:=Plan.new().build(settings);check(plan.ok,"legacy fort plan")
	var manifest:={"version":1,"settings":settings,"parts":[]}
	for r in plan.records:doc.records.append(r);manifest.parts.append({"id":r.uuid,"signature":Layout.token(r)})
	doc.map_meta.editor_layout=Layout.defaults();doc.map_meta.editor_layout.fortifications=[manifest]
	var bridge:=preload("res://scripts/world_editor/bridge_tools.gd").make_record({"id":"legacy_bridge","start":[-12,0,25],"end":[12,0,25]},preload("res://scripts/world3d/bridge_data.gd").preset("stone_segmental"))
	var library=preload("res://scripts/world_editor/surface_material_library.gd").new()
	var defaults:=preload("res://scripts/world3d/bridge_data.gd").default_materials()
	for role in defaults:bridge.bridge_materials[role]=library.find(defaults[role])
	doc.records.append(bridge)
	check(doc.save(path)==OK,"temporary legacy structures saved")
	Net.session().world3d_editor_path=path;Net.session().world3d_editor_doc=doc
	editor=preload("res://scripts/world_editor/world_editor.gd").new();editor._mcp_autostart=false;editor._draft_directory=directory.path_join("drafts");root.add_child(editor);await physics();editor._safety.enabled=false
	var probe:=TCPServer.new()
	while probe.listen(port,"127.0.0.1")!=OK:port+=1
	probe.stop();check(editor.start_mcp(port).ok,"true HTTP MCP")
	var discovery:=await rpc("tools/list")
	for name in ["bake_fortification","bake_bridge"]:check(discovery.result.tools.any(func(t):return t.name==name),"discover "+name)
	var before:=doc.recovery_snapshot();var history:int=doc._undo.size()
	await call_tool("bake_fortification",{"id":"missing"},false);await call_tool("bake_bridge",{"id":"missing"},false)
	check(doc.recovery_snapshot()==before and doc._undo.size()==history,"invalid calls do not mutate")
	await call_tool("bake_fortification",{"id":"legacy_wall"})
	var baked:Array=doc.records.filter(func(r):return r.has("fortification"))
	check(baked.size()<plan.records.size() and baked.all(func(r):return Frozen.valid(r) and r.has("house_prefab")),"fortification becomes fixed components")
	var leaves:Array=baked.filter(func(r):return r.has("fixture"))
	check(leaves.size()==2 and leaves[0].fixture.angle*leaves[1].fixture.angle<0,"opposed gate leaves retain independent hinges")
	var fixed:Array=doc.records.duplicate(true)
	await call_tool("undo");check(doc.records==before.records,"undo migration restores originals")
	await call_tool("redo");check(doc.records==fixed,"redo migration restores exact payload")
	await call_tool("set_fortification_gate",{"id":"legacy_wall","gate_id":"gate","open":0.0})
	check(doc.records.filter(func(r):return r.has("fortification") and r.has("fixture")).all(func(r):return r.fixture.open==0.0),"fixed gate operates without regeneration")
	check((await call_tool("list_fortifications")).regions[0].modified_or_missing.is_empty(),"gate state updates manifest signatures")
	await call_tool("undo")
	before=doc.recovery_snapshot();history=doc._undo.size()
	await call_tool("generate_fortification",{"id":"legacy_wall","height":9},false)
	await call_tool("remove_fortification",{"id":"legacy_wall","keep_objects":true},false)
	await call_tool("set_object_transform",{"id":baked[0].uuid,"position":[0,0,0]},false)
	check(doc.recovery_snapshot()==before and doc._undo.size()==history,"fixed structure edits fail without side effects")
	await call_tool("bake_bridge",{"id":"legacy_bridge"})
	check(Frozen.valid(doc._find("legacy_bridge")) and doc._find("legacy_bridge").prefab_locked,"bridge baked locally with original transform")
	var expected_mesh:Mesh=preload("res://scripts/world3d/bridge_mesh.gd").new().build(bridge)
	var actual:Dictionary=Frozen.geometry(doc._find("legacy_bridge"))
	check(expected_mesh.get_faces()==actual.source.get_faces(),"bridge collision triangles remain exact including arches")
	before=doc.recovery_snapshot();history=doc._undo.size()
	await call_tool("generate_bridge",{"id":"legacy_bridge","start":[-12,0,25],"end":[12,0,25],"width":9},false)
	check(doc.recovery_snapshot()==before and doc._undo.size()==history,"cannot regenerate fixed bridge")
	await call_tool("set_object_properties",{"ids":[baked[0].uuid],"locked":true})
	before=doc.recovery_snapshot();await call_tool("remove_fortification",{"id":"legacy_wall","keep_objects":false},false);check(doc.recovery_snapshot()==before,"protected prefab cannot be deleted")
	await call_tool("undo")
	# New placements also bake automatically, rather than only migrated instances.
	await call_tool("generate_fortification",{"id":"new_wall","points":[[-20,50],[20,50]],"closed":false,"style":"plain","corner_towers":false,"battlements":true})
	check(doc.records.filter(func(r):return r.get("fortification",{}).get("id","")=="new_wall").all(func(r):return r.has("house_prefab")),"new fortification auto baked")
	await call_tool("generate_bridge",{"id":"new_bridge","start":[-12,0,0],"end":[12,0,0],"width":6,"depth":4})
	check(doc._find("new_bridge").has("house_prefab"),"new bridge auto baked")
	var saved:Array=doc.records.duplicate(true)
	await call_tool("save_world");await call_tool("open_world",{"path":path});doc=editor._doc
	check(equivalent(doc.records,saved),"save reopen fixed payload and identity")
	check((await call_tool("list_fortifications")).regions.all(func(r):return r.baked and r.modified_or_missing.is_empty()),"all manifests intact after reopen")
	editor.free();Net.session().world3d_editor_doc=null;Net.session().world3d_editor_path=""
	print("STRUCTURE_PREFAB_MCP_FINISHED failures=",failed);quit(1 if failed else 0)
