extends "res://tools/test_world3d_mcp.gd"
const Net = preload("res://scripts/net/net.gd")
const Settings = preload("res://scripts/world3d/editor_view_settings.gd")
var directory: String
func wait_phase(expected: String, seconds: float = 60) -> void:
	var deadline := Time.get_ticks_msec()+int(seconds*1000)
	while editor._playtest.phase != expected and editor._playtest.phase != "failed" and Time.get_ticks_msec()<deadline: await process_frame
	check(editor._playtest.phase == expected,"playtest phase "+expected+" ("+editor._playtest.last_error+")")
func physics() -> void:
	await settle(); await physics_frame; await physics_frame
func run() -> void:
	create_timer(145).timeout.connect(func(): push_error("Playtest acceptance timeout"); quit(2))
	root.size = Vector2i(1280,800); root.content_scale_size = root.size
	directory = Paths.cache_directory("playtest_acceptance_%d_%d" % [OS.get_process_id(),Time.get_ticks_usec()])
	var path := directory.path_join("map.gltf")
	var doc := Doc.new()
	var lower: String = doc.add_box("ground",Vector3(0,-.1,0),Vector3(20,.2,20))
	var upper: String = doc.add_box("ground",Vector3(0,2.9,0),Vector3(8,.2,8))
	var a: String = doc.add_box("block",Vector3(2,.5,0),Vector3.ONE)
	var b: String = doc.add_box("block",Vector3(2,3.5,0),Vector3.ONE)
	check(doc.save(path) == OK,"create isolated two-storey fixture")
	Net.session().world3d_editor_path = path; Net.session().world3d_editor_doc = doc
	preload("res://tools/world3d_test_character.gd").ensure(self)
	editor = preload("res://scripts/world_editor/world_editor.gd").new(); editor._mcp_autostart = false; editor._draft_directory = directory.path_join("drafts")
	root.add_child(editor); await physics(); editor._safety.enabled = false
	var probe := TCPServer.new()
	while probe.listen(port,"127.0.0.1") != OK: port += 1
	probe.stop(); check(editor.start_mcp(port).ok,"start real HTTP MCP")
	var discovery := await rpc("tools/list")
	check(discovery.result.tools.size() == 118,"discover all 118 current 3D tools")
	await call_tool("get_editor_view")
	await call_tool("set_floor_view",{"isolation":true,"base_height":0,"floor_height":3,"outside":"hide"})
	await physics()
	check(editor._view.get_node(a).visible and not editor._view.get_node(b).visible and not editor._view.get_node(upper).visible,"floor zero shows its objects and hides the ceiling and upper floor")
	check(editor._bodies_by_uuid.has(lower) and not editor._bodies_by_uuid.has(upper),"other-floor collision cannot intercept editor picking")
	await call_tool("select_objects",{"ids":[b]},false)
	var before := doc.recovery_snapshot(); var history: int = doc._undo.size()
	await call_tool("set_object_transform",{"id":b,"position":[2,4,0]},false)
	await call_tool("set_event_template",{"id":b,"parameters":{"text":"不可修改"}},false)
	await call_tool("set_floor_view",{"floor_height":0},false)
	await call_tool("set_playtest_spawn",{"position":[0,0]},false)
	check(doc.recovery_snapshot() == before and doc._undo.size() == history,"off-floor and malformed edits leave document/history unchanged")
	var available := await call_tool("list_assets")
	var basic: Array = available.assets.filter(func(entry): return not entry.prefab and str(entry.auto_family).is_empty())
	check(not basic.is_empty(),"basic placement module available")
	if not basic.is_empty():
		var count_before: int = doc.records.size()
		var placed := await call_tool("place_asset",{"asset_id":basic[0].asset_id,"position":[5,6,0]})
		check(placed.ids.size() == 1 and doc.records.size() == count_before+1 and not editor._selection_tools.ids.has(placed.ids[0]),"MCP returns the created ID even when placement is outside the active floor")
		await call_tool("undo")
		check(doc.records.size() == count_before,"off-floor placement shares normal undo")
	await call_tool("set_floor_view",{"outside":"dim"}); await physics()
	check(editor._view.get_node(b).visible and editor._view.get_node(b).transparency>.8 and not editor._bodies_by_uuid.has(b),"dimmed storey is visible but not pickable")
	await call_tool("set_floor_view",{"base_height":3})
	check(editor._view.get_node(upper).visible and editor._record_editable(doc._find(b)) and not editor._record_editable(doc._find(a)),"switching floors changes editable objects")
	await call_tool("undo")
	check(editor._authoring.settings.base_height == 0,"floor view shares document undo")
	await call_tool("redo"); await call_tool("undo")
	await call_tool("set_object_properties",{"ids":[a],"locked":true})
	await call_tool("set_object_transform",{"id":a,"position":[2,3.5,1]},false)
	await call_tool("set_object_properties",{"ids":[a],"locked":false})
	await call_tool("set_object_transform",{"id":a,"position":[2,3.5,1]})
	check(not editor._record_editable(doc._find(a)) and not editor._selection_tools.ids.has(a),"moving an object to another storey updates membership and selection")
	await call_tool("undo")
	editor._top_view(); await physics()
	var screen: Vector2 = editor._camera.unproject_position(Vector3(-2,0,0))
	await call_tool("pick_playtest_spawn",{"screen":[screen.x,screen.y]})
	check(absf(float(editor._authoring.settings.spawn[1]))<.01,"screen picking chooses the visible floor, not hidden ceiling")
	await call_tool("set_playtest_spawn",{"position":[0,0,0]})
	# Real mouse placement and Escape cancellation use the same undoable setting.
	if DisplayServer.get_name() != "headless":
		editor._authoring.begin_pick()
		var click := InputEventMouseButton.new(); click.button_index = MOUSE_BUTTON_LEFT; click.pressed = true; click.position = editor._canvas.global_position+screen
		Input.parse_input_event(click); await physics()
		check(not editor._authoring.picking and absf(float(editor._authoring.settings.spawn[0])+2)<.05,"real canvas click sets the spawn point")
		var picked: Array = editor._authoring.settings.spawn.duplicate()
		editor._authoring.begin_pick()
		var escape := InputEventKey.new(); escape.pressed = true; escape.keycode = KEY_ESCAPE; Input.parse_input_event(escape); await physics()
		check(not editor._authoring.picking and editor._authoring.settings.spawn == picked,"Escape cancels spawn picking without editing")
		await call_tool("set_playtest_spawn",{"position":[0,0,0]})
	await call_tool("undo"); await call_tool("redo")
	await call_tool("save_world")
	await call_tool("open_world",{"path":path})
	doc = editor._doc
	check(editor._authoring.settings.isolation and equivalent(editor._authoring.settings.spawn,[0,0,0]),"save/reopen preserves floor and spawn preferences")
	# The reward exists only in unsaved memory, and must appear in the temporary map.
	var reward := await call_tool("create_event_template",{"template":"chest","position":[-2,0,1],"parameters":{"gold":71}})
	await call_tool("select_objects",{"ids":[a]})
	before = doc.recovery_snapshot(); history = doc._undo.size()
	var map_hash := FileAccess.get_sha256(path)
	var selection: Array = editor._selection_tools.ids.duplicate()
	var camera: Transform3D = editor._camera.transform
	var source = Net.server()
	var inventory: Dictionary = source.inventory.capture_session_state()
	var switches: Dictionary = source.world3d_events.runtime.self_switches.duplicate(true)
	var session_spawn: Dictionary = Net.session().spawn_data.duplicate(true)
	if DisplayServer.get_name() == "headless":
		await call_tool("start_playtest",{},false)
	else:
		var queued: Dictionary = editor._playtest.start()
		var cancelled_path: String = queued.temporary_path
		editor._playtest.stop(); await wait_phase("idle")
		check(not FileAccess.file_exists(cancelled_path) and Net.server() == source,"cancel during preparation removes temporary files without entering a session")
		await call_tool("start_playtest",{"position":[0,3.5,0]})
		await wait_phase("failed")
		check(Net.server() == source and doc.recovery_snapshot() == before and FileAccess.get_sha256(path) == map_hash,"unsupported spawn fails without changing session or document")
		await call_tool("start_playtest",{"position":[2,0,0]}); await wait_phase("failed")
		check(Net.server() == source and doc._undo.size() == history,"capsule collision rejects a blocked spawn without side effects")
		await call_tool("start_playtest")
		await wait_phase("running")
		if editor._playtest.phase == "running":
			var state := await call_tool("playtest_state")
			check(FileAccess.file_exists(state.temporary_path) and state.temporary_path != path and Net.server() != source,"running preview uses a temporary file and private server")
			check(editor._playtest.world._map_root.get_meta("stream_library").size() == doc.records.size(),"preview contains all floors and unsaved objects")
			Net.server().world3d_events.run(reward.id)
			check(Net.server().inventory.get_gold() == int(inventory.gold)+71 and source.inventory.capture_session_state() == inventory,"test reward affects only preview inventory")
			check(source.world3d_events.runtime.self_switches == switches,"formal event switches remain untouched")
			var destination := Doc.new(); destination.add_box("ground",Vector3(0,-.1,0),Vector3(20,.2,20))
			var destination_path := directory.path_join("destination/map.gltf")
			check(destination.save(destination_path) == OK,"create isolated transfer destination")
			check(await editor._playtest.world.transfer_map(destination_path,Vector3(0,.9,0)),"preview can transfer to another map")
			check(await editor._playtest.world.transfer_map(path,Vector3(0,.9,0)) and editor._playtest.world._map_path == state.temporary_path,"return transfer uses unsaved temporary map instead of formal disk version")
			check(Net.server().world3d_events.targets.has(reward.id),"return map still contains unsaved event")
			Net.server().world3d_events.run(reward.id)
			check(Net.server().inventory.get_gold() == int(inventory.gold)+71,"one-shot reward state survives preview map transfers")
			await call_tool("set_environment",{"preset":"night"},false)
			await call_tool("save_world",{},false)
			await call_tool("set_floor_view",{"base_height":3},false)
			await RenderingServer.frame_post_draw
			root.get_texture().get_image().save_png(preload("res://scripts/asset/art_paths.gd").review_path("editor_playtest/running.png"))
			var temporary: String = state.temporary_path
			await call_tool("stop_playtest"); await wait_phase("idle")
			check(not FileAccess.file_exists(temporary) and Net.server() == source,"stop removes only the owned temporary map and restores real server")
			check(equivalent(Net.session().spawn_data,session_spawn) and source.inventory.capture_session_state() == inventory and source.world3d_events.runtime.self_switches == switches,"stop restores client session without modifying real gameplay progress")
			check(doc.recovery_snapshot() == before and doc._undo.size() == history and editor._dirty and editor._selection_tools.ids == selection and editor._camera.transform == camera,"dirty document, undo history, selection and camera survive preview")
			check(FileAccess.get_sha256(path) == map_hash,"formal map was never saved by playtest")
			await call_tool("start_playtest"); await wait_phase("running")
			if editor._playtest.phase == "running":
				Net.session().go_world_editor(); await wait_phase("idle")
				check(Net.server() == source and is_instance_valid(editor),"game return-to-editor action stops preview instead of recreating editor")
			editor._dock_tabs.current_tab = 7; await physics(); await RenderingServer.frame_post_draw
			root.get_texture().get_image().save_png(preload("res://scripts/asset/art_paths.gd").review_path("editor_playtest/panel.png"))
	await call_tool("playtest_state")
	if editor._playtest.active(): editor._playtest.stop(); await wait_phase("idle")
	editor.free()
	Net.session().world3d_editor_doc = null; Net.session().world3d_editor_path = ""
	if failed == 0: Io._remove_tree(directory)
	else: print("fixture="+directory)
	print("test_world3d_playtest: %s" % ("PASS" if failed == 0 else "FAIL"))
	quit(0 if failed == 0 else 1)
