extends SceneTree
const Doc=preload("res://scripts/world3d/world_document.gd")
const Io=preload("res://scripts/world3d/gltf_map_io.gd")
const Paths=preload("res://scripts/world3d/map_paths.gd")
const Writer=preload("res://scripts/world3d/reference_map_save.gd")
var failures:=0
func _init()->void:call_deferred("run")
func check(value:bool,label:String)->void:
	print("PASS " if value else "FAIL ",label)
	if not value:failures+=1
func run()->void:
	var directory:=Paths.cache_directory("reference_recovery_%d"%Time.get_ticks_usec())
	var path:=directory.path_join("map.gltf")
	var doc:=Doc.new();var id:String=doc.add_box("block",Vector3.ZERO,Vector3.ONE)
	check(doc.save(path)==OK,"initial reference save")
	doc.move(id,Vector3(3,2,1));check(doc.save(path)==OK,"second reference save")
	check(Io.restore_previous(path)==OK,"restore validates resources against original map filename")
	var reopened=Doc.open_file(path)
	check(reopened!=null and Vector3(reopened.records[0].position[0],reopened.records[0].position[1],reopened.records[0].position[2])==Vector3.ZERO,"previous authored pose restored")
	check(Io.restore_previous(path)==OK,"restore remains reversible")
	reopened=Doc.open_file(path)
	check(reopened!=null and reopened.records[0].position==[3.0,2.0,1.0],"second pose retained in previous checkpoint")
	var legacy:Dictionary={"asset":{"version":"2.0"},"scene":0,"scenes":[{"nodes":[0]}],"nodes":[{"name":"rmmo_world","extras":{"rmmo_format":"rmmo_gltf_map","rmmo_version":1,"rmmo_unit":"m","rmmo_records":doc.records}}]}
	var file:=FileAccess.open(path+".previous",FileAccess.WRITE);file.store_string(JSON.stringify(legacy));file.close()
	check(Io.restore_previous(path)==OK,"migration v1 checkpoint restored through v2 writer")
	var raw:Dictionary=JSON.parse_string(FileAccess.get_file_as_string(path))
	check(raw.nodes[0].extras.rmmo_version==2 and raw.nodes[0].extras.rmmo_storage=="references_v1","restore never republishes old native format")
	var author:Dictionary=Doc.authoritative_extras(path)
	check(author.has("extras") and author.extras.rmmo_records[0].get("kind")=="box" and not author.extras.rmmo_records[0].has("rmmo_ref"),"shared authoring API restores complete records for existing editing tools")
	var metadata:Dictionary=Doc.authoritative_extras(path,null,true)
	check(metadata.has("extras") and not metadata.extras.has("rmmo_records"),"weather-only API avoids hydrating and exposing compact records")
	var before:=FileAccess.get_sha256(path)
	var valid_previous:=FileAccess.get_file_as_bytes(path+".previous")
	var invalid_native:Dictionary=raw.duplicate(true);invalid_native.nodes[0].extras.erase("rmmo_storage")
	file=FileAccess.open(path+".previous",FileAccess.WRITE);file.store_string(JSON.stringify(invalid_native));file.close()
	check(Io.restore_previous(path)==ERR_INVALID_DATA and FileAccess.get_sha256(path)==before,"malformed native checkpoint cannot bypass validation through generic glTF fallback")
	file=FileAccess.open(path+".previous",FileAccess.WRITE);file.store_buffer(valid_previous);file.close()
	var previous:Dictionary=JSON.parse_string(FileAccess.get_file_as_string(path+".previous"))
	var uri:String=previous.nodes[0].extras.rmmo_records[0].rmmo_ref.uri
	var resource:=directory.path_join(uri);var bytes:=FileAccess.get_file_as_bytes(resource)
	file=FileAccess.open(resource,FileAccess.WRITE);file.store_string("corrupt");file.close()
	check(Io.restore_previous(path)!=OK and FileAccess.get_sha256(path)==before,"bad previous resource cannot replace current map")
	file=FileAccess.open(resource,FileAccess.WRITE);file.store_buffer(bytes);file.close()
	DirAccess.remove_absolute(path)
	check(Io.restore_previous(path)==OK and Doc.open_file(path)!=null,"missing live file can recover from valid reference checkpoint")
	for hidden in ["map.gltf.versions/old","map.gltf.resources","map.gltf.save-lock"]:
		DirAccess.make_dir_recursive_absolute(directory.path_join(hidden))
		file=FileAccess.open(directory.path_join(hidden).path_join("map.gltf"),FileAccess.WRITE);file.store_string("{}");file.close()
	var catalog=preload("res://scripts/world_editor/resource_pack_catalog.gd").new()
	var available:Array[Dictionary]=[]
	catalog._collect_maps(directory,directory,{},available,0)
	check(available.size()==1 and available[0].path==path,"map picker excludes old save generations and private resource storage")
	Io._remove_tree(directory)
	print("REFERENCE_RECOVERY_FINISHED failures=",failures)
	quit(0 if failures==0 else 1)
