extends "res://tools/test_world3d_mcp.gd"
const Rules = preload("res://scripts/world3d/auto_tile_rules.gd")

func settle_physics() -> void:
	await settle()
	await physics_frame
	await process_frame

func position(id: String) -> Vector3: return Geometry.vector(editor._doc._find(id), "position")

func bounds(id: String) -> AABB: return Geometry.bounds([editor._doc._find(id)])

func key(code: Key, shift: bool = false) -> void:
	var event := InputEventKey.new()
	event.keycode = code
	event.pressed = true
	event.shift_pressed = shift
	Input.parse_input_event(event)
	await settle_physics()

func screen_click(point: Vector2) -> void:
	for pressed in [true, false]:
		var event := InputEventMouseButton.new()
		event.button_index = MOUSE_BUTTON_LEFT
		event.pressed = pressed
		event.position = editor._canvas.global_position + point
		Input.parse_input_event(event)
		await settle_physics()

func capture(name_: String) -> void:
	await settle_physics()
	await RenderingServer.frame_post_draw
	var path: String = preload("res://scripts/asset/art_paths.gd").review_path("editor_placement/" + name_ + ".png")
	root.get_texture().get_image().save_png(path)
	print("capture=" + path)

func run() -> void:
	root.size = Vector2i(1280, 800)
	root.content_scale_size = root.size
	var directory := Paths.cache_directory("placement_%d" % Time.get_ticks_usec())
	var path := directory.path_join("map.gltf")
	var doc := Doc.new()
	var floor_id: String = doc.add_box("ground", Vector3(0, -0.1, 0), Vector3(60, 0.2, 60))
	doc._find(floor_id).editor_locked = true
	var a: String = doc.add_box("block", Vector3(-6, 5, 0), Vector3(2, 2, 2))
	var b: String = doc.add_box("block", Vector3(0, 6, 0), Vector3(3, 2, 2))
	var c: String = doc.add_box("block", Vector3(8, 7, 0), Vector3(4, 4, 2))
	var ramp: String = doc.add_box("ramp", Vector3(0, 1, -12), Vector3(10, 0.3, 10), Vector3(25, 0, 0))
	var session = preload("res://scripts/net/net.gd").session()
	session.world3d_editor_path = path
	session.world3d_editor_doc = doc
	editor = preload("res://scripts/world_editor/world_editor.gd").new()
	editor._mcp_autostart = false
	root.add_child(editor)
	await settle_physics()
	editor._camera.position = Vector3(16, 18, -28)
	editor._camera.look_at(Vector3(0, 1, -6))
	var probe := TCPServer.new()
	while probe.listen(port, "127.0.0.1") != OK: port += 1
	probe.stop()
	check(editor.start_mcp(port).ok, "start placement HTTP fixture")
	var discovery := await rpc("tools/list")
	var names: Array = discovery.result.tools.map(func(tool): return tool.name)
	check(["drop_selection", "snap_selection_to_surface", "align_selection", "distribute_selection"].all(func(name_): return names.has(name_)), "all four placement tools advertised")
	await call_tool("select_objects", {"ids": [a, b, c]})
	var before: Array = editor._doc.records.duplicate(true)
	var history: int = editor._doc._undo.size()
	await call_tool("align_selection", {"axis": "y", "anchor": "min"})
	check(is_equal_approx(bounds(a).position.y, 5) and is_equal_approx(bounds(b).position.y, 5) and position(c) == Vector3(8, 7, 0), "bottom alignment uses last selected object's edge and leaves reference fixed")
	check(editor._doc._undo.size() == history + 1, "alignment is one undo transaction")
	await call_tool("undo")
	check(editor._doc.records == before, "alignment undo restores complete records")
	await call_tool("distribute_selection", {"axis": "x", "spacing": "gaps"})
	var gap1 := bounds(b).position.x - bounds(a).end.x
	var gap2 := bounds(c).position.x - bounds(b).end.x
	check(is_equal_approx(gap1, gap2) and position(a).x == -6 and position(c).x == 8, "unequal-size objects distribute with equal edge gaps and fixed endpoints")
	await call_tool("undo")
	await call_tool("distribute_selection", {"axis": "x", "spacing": "centers"})
	check(is_equal_approx(position(b).x, 1), "equal-center distribution uses center spacing")
	await call_tool("undo")
	await call_tool("set_object_transform", {"id": c, "size": [40, 4, 2]})
	await call_tool("select_objects", {"ids": [a, b, c]})
	var overlap: Array = editor._doc.records.duplicate(true)
	history = editor._doc._undo.size()
	await call_tool("distribute_selection", {"axis": "x", "spacing": "gaps"}, false)
	check(editor._doc.records == overlap and editor._doc._undo.size() == history, "insufficient distribution space leaves records and history untouched")
	await call_tool("set_object_transform", {"id": c, "size": [4, 4, 2]})
	await call_tool("select_objects", {"ids": [a, b, c]})
	await call_tool("drop_selection")
	check(is_zero_approx(bounds(a).position.y) and is_zero_approx(bounds(b).position.y) and is_zero_approx(bounds(c).position.y), "each ungrouped object lands on locked floor without hitting selected peers")
	history = editor._doc._undo.size()
	await call_tool("drop_selection")
	check(editor._doc._undo.size() == history, "already grounded objects do not create empty undo steps")
	await call_tool("undo")
	check(editor._doc.records == before, "drop undo restores all objects together")
	await call_tool("select_objects", {"ids": [a, b]})
	await call_tool("group_selection")
	var relative := position(b) - position(a)
	await call_tool("drop_selection")
	check((position(b) - position(a)).is_equal_approx(relative) and is_zero_approx(Geometry.bounds(editor._selection_tools.records()).position.y), "complete group drops as a rigid unit")
	await call_tool("undo")
	await call_tool("select_objects", {"ids": [a]})
	before = editor._doc.records.duplicate(true)
	history = editor._doc._undo.size()
	await call_tool("drop_selection", {}, false)
	await call_tool("align_selection", {"axis": "x"}, false)
	check(editor._doc.records == before and editor._doc._undo.size() == history, "partial group is rejected atomically")
	await call_tool("select_objects", {"ids": [a, b, c]})
	await call_tool("align_selection", {"axis": "z", "anchor": "max"})
	check((position(b) - position(a)).is_equal_approx(relative), "alignment preserves group member spacing")
	await call_tool("ungroup_selection")
	# One missing support must not commit earlier successful placements.
	await call_tool("set_object_transform", {"id": c, "position": [50, 7, 0]})
	await call_tool("select_objects", {"ids": [a, c]})
	before = editor._doc.records.duplicate(true)
	history = editor._doc._undo.size()
	await call_tool("drop_selection", {}, false)
	await call_tool("drop_selection", {"max_distance": -1}, false)
	await call_tool("align_selection", {"axis": "w"}, false)
	await call_tool("snap_selection_to_surface", {"screen": [100000, 100000]}, false)
	check(editor._doc.records == before and editor._doc._undo.size() == history, "missing surfaces and invalid arguments preserve document/history")
	await call_tool("set_object_transform", {"id": c, "position": [8, 7, 0]})
	await call_tool("set_object_transform", {"id": a, "position": [0, 9, -12], "rotation": [0, 35, 0]})
	await settle_physics()
	await call_tool("drop_selection", {"align_normal": true, "offset": 0.15})
	var normal := Basis.from_euler(Vector3(25, 0, 0) * PI / 180).y
	var plane_point := position(ramp) + normal * 0.15
	var rotated := Basis.from_euler(Geometry.vector(editor._doc._find(a), "rotation") * PI / 180)
	check(rotated.y.dot(normal) > 0.109109 and is_equal_approx(editor._placement_tools._distance([editor._doc._find(a)], plane_point, normal), 0.15), "drop matches actual slope normal and keeps requested surface clearance")
	await call_tool("undo")
	await call_tool("redo")
	check(Basis.from_euler(Geometry.vector(editor._doc._find(a), "rotation") * PI / 180).y.dot(normal) > 0.9999, "redo restores slope orientation")
	await call_tool("select_objects", {"ids": [b]})
	var target := plane_point + Vector3(2.5, 0, 0)
	var screen: Vector2 = editor._camera.unproject_position(target)
	var visible_hit: Dictionary = editor._placement_tools._screen_hit(screen)
	check(not visible_hit.is_empty() and str(visible_hit.collider.get_meta("uuid", "")) == ramp, "surface test targets an unobstructed slope")
	await call_tool("snap_selection_to_surface", {"screen": [screen.x, screen.y], "align_normal": true})
	check(is_zero_approx(editor._placement_tools._distance([editor._doc._find(b)], plane_point, normal)), "point placement rests on clicked slope plane")
	# Actual GLB with offset origin and nonuniform scale.
	var source := Node3D.new()
	var mesh := MeshInstance3D.new()
	mesh.mesh = BoxMesh.new()
	mesh.position = Vector3(0.4, 1, 0)
	source.add_child(mesh)
	var model_path := directory.path_join("model.glb")
	check(Io.save_scene(source, model_path) == OK, "create imported placement fixture")
	source.free()
	var imported := preload("res://scripts/world_editor/asset_library.gd").new(directory.path_join("assets")).import_file(model_path)
	check(imported.ok, "import offset-origin model")
	var model: String = editor._doc.add_asset(imported.entry, Vector3(-10, 8, -6))
	editor._doc._find(model).size = [1.5, 0.75, 2]
	editor._doc._find(model).rotation = [0, 30, 0]
	editor._rebuild()
	await settle_physics()
	await call_tool("select_objects", {"ids": [model]})
	await call_tool("drop_selection")
	check(is_zero_approx(bounds(model).position.y) and Geometry.vector(editor._doc._find(model), "size").is_equal_approx(Vector3(1.5, 0.75, 2)), "GLB bounds offset and nonuniform scale survive grounding")
	await settle_physics()
	await call_tool("select_objects", {"ids": [c]})
	var model_top := bounds(model).get_center()
	model_top.y = bounds(model).end.y
	screen = editor._camera.unproject_position(model_top)
	visible_hit = editor._placement_tools._screen_hit(screen)
	check(not visible_hit.is_empty() and str(visible_hit.collider.get_meta("uuid", "")) == model, "surface picking hits real imported mesh triangles")
	await call_tool("snap_selection_to_surface", {"screen": [screen.x, screen.y], "offset": 0.1})
	check(is_equal_approx(bounds(c).position.y, model_top.y + 0.1), "surface placement lands on scaled GLB instead of floor behind it")
	await call_tool("undo")
	await settle_physics()
	# The auto-tile detaches only if its transform actually changes.
	var tile: String = editor._doc.add_box_silent("ground", Vector3.ZERO, Vector3.ONE)
	Rules.configure(editor._doc._find(tile), Vector2i(10, 10), "road", 1, 5)
	Rules.refresh_all(editor._doc.records)
	editor._rebuild()
	await settle_physics()
	await call_tool("select_objects", {"ids": [tile]})
	await call_tool("drop_selection")
	check(not Rules.attached(editor._doc._find(tile)), "grounding freezes moved auto-tile geometry")
	await call_tool("undo")
	check(Rules.attached(editor._doc._find(tile)), "undo restores auto-tile membership")
	await call_tool("select_objects", {"ids": [c]})
	editor._placement_tools.begin_surface()
	await call_tool("drop_selection", {}, false)
	var state := await call_tool("editor_state")
	check(state.surface_placement_active, "MCP reports pending surface interaction and rejects conflicting edit")
	editor._placement_tools.cancel()
	if DisplayServer.get_name() != "headless":
		await key(KEY_END)
		check(is_zero_approx(bounds(c).position.y), "End shortcut grounds selected object through real input")
		before = editor._doc.records.duplicate(true)
		history = editor._doc._undo.size()
		await key(KEY_V)
		check(editor._placement_tools.active, "V enters surface picking")
		await key(KEY_ESCAPE)
		check(not editor._placement_tools.active and editor._doc.records == before and editor._doc._undo.size() == history, "Esc cancels point placement without mutating history")
		await key(KEY_V)
		await screen_click(editor._camera.unproject_position(plane_point - Vector3(2.5, 0, 0)))
		check(not editor._placement_tools.active and Basis.from_euler(Geometry.vector(editor._doc._find(c), "rotation") * PI / 180).y.dot(normal) > 0.109109, "real click places object on slope and exits picking")
		editor._selection_tools.set_ids([a, b, c])
		editor._show_placement_panel()
		await settle_physics()
		var panel: AcceptDialog = editor.get_node("PlacementDialog")
		var axis: OptionButton = panel.find_child("ArrangeAxis", true, false)
		axis.select(1)
		var align_button: Button = panel.find_child("AlignSelection", true, false)
		align_button.pressed.emit()
		check(is_equal_approx(bounds(a).get_center().y, bounds(c).get_center().y), "dialog connects axis and anchor to shared alignment command")
		await capture("placement_dialog")
		panel.queue_free()
		await settle_physics()
		root.size = Vector2i(1024, 720)
		root.content_scale_size = root.size
		await settle_physics()
		check(editor._canvas.size.x > 450 and editor._canvas.size.y > 350, "placement controls fit 1024 pixel workspace")
		await capture("placement_1024")
	await call_tool("save_world")
	before = editor._doc.records.duplicate(true)
	await call_tool("open_world", {"path": path})
	check(equivalent(editor._doc.records, before), "placement results and model transforms persist through glTF reopen")
	editor._mcp.stop()
	editor.queue_free()
	await settle()
	session.world3d_editor_doc = null
	session.world3d_editor_path = ""
	Io._remove_tree(directory)
	print("test_world3d_placement: %s" % ("PASS" if failed == 0 else "FAIL (%d)" % failed))
	quit(0 if failed == 0 else 1)
