extends "res://tools/test_ground_batching.gd"
const Bank=preload("res://scripts/world3d/rock_bank_mesh.gd")
const Author=preload("res://tools/arrange_bridge_terrain.gd")
const OUT="D:/code/rmmo_runtime/review_artifacts/rock_bank_batching"
func run()->void:
	create_timer(240).timeout.connect(func():quit(2));Engine.max_fps=120
	DirAccess.make_dir_recursive_absolute(OUT)
	viewport=SubViewport.new();viewport.size=Vector2i(1280,720);viewport.own_world_3d=true;viewport.render_target_update_mode=SubViewport.UPDATE_ALWAYS;root.add_child(viewport)
	var light:=DirectionalLight3D.new();light.rotation_degrees=Vector3(-55,32,0);viewport.add_child(light)
	camera=Camera3D.new();viewport.add_child(camera);camera.position=Vector3(300,28,200);camera.look_at(Vector3(305,0,160))
	var doc:=Doc.new();var records:Array=Doc.authoritative_extras(Author.MAP_BANK).extras.rmmo_records.filter(func(r):return r.has("rock_bank"))
	check(records.size()==2,"two authored banks")
	var hashes:Array=[];var triangles:=0
	for record:Dictionary in records:
		var scaled:Dictionary=record.duplicate(true);scaled.size[1]=3
		check(Batch.Geometry.candidate(scaled),"tall/scaled banks retain explicit batching eligibility")
		var node:MeshInstance3D=doc._mesh(record);viewport.add_child(node);sources.append(node)
		hashes.append(var_to_bytes(node.mesh.get_faces()).hex_encode().sha256_text());triangles+=node.mesh.get_faces().size()/3
		var prepared:=Bank.mesh(record,Bank.arrays(record))
		check(prepared.get_faces()==node.mesh.get_faces(),"worker arrays reproduce source mesh")
	RenderingServer.viewport_set_measure_render_time(viewport.get_viewport_rid(),true)
	var report:={"triangles":triangles,"before":await measure()}
	await RenderingServer.frame_post_draw;var before:=viewport.get_texture().get_image();before.save_png(OUT+"/before.png")
	var batch:=Batch.new();viewport.add_child(batch);batch.sync(sources);batch.flush()
	report.after=await measure();report.stats=batch.stats()
	await RenderingServer.frame_post_draw;var after:=viewport.get_texture().get_image();after.save_png(OUT+"/after.png")
	report.pixel_error=difference(before,after)
	check(report.stats.source_objects==2 and report.stats.render_surfaces==2,"actual banks automatically merge four surfaces into two")
	check(report.after.draw_calls<report.before.draw_calls,"rendered draw calls decrease")
	check(report.pixel_error<.004,"appearance preserved")
	for i in sources.size():
		check(sources[i].mesh is Cpu,"merged source releases GPU mesh")
		check(var_to_bytes(sources[i].mesh.get_faces()).hex_encode().sha256_text()==hashes[i],"exact collision/source triangles preserved")
	var builds:int=batch.rebuild_count;batch.sync(sources);batch.flush();check(builds==batch.rebuild_count,"unchanged scene never rebuilds")
	batch.sync(sources,[str(sources[0].name)]);batch.flush();check(not sources[0].mesh is Cpu,"selection restores independently editable mesh")
	batch.clear();viewport.queue_free();await process_frame
	# A unique temporary map forces uncooked loading; it never changes the user map.
	var temporary:=preload("res://scripts/world3d/map_paths.gd").cache_directory("rock_batch_%d"%Time.get_ticks_usec())+"/map.gltf"
	doc.records=records;check(doc.save(temporary)==OK,"temporary native map saved")
	var loader:=preload("res://scripts/world3d/map_loader.gd").new();root.add_child(loader);loader.start(temporary)
	var loaded:Array=await loader.finished
	check(loaded[0]!=null,"native async loader succeeds")
	check(loader._surface_arrays.size()==2,"both native banks generated by background geometry workers")
	report.load_profile=loader._profile
	if loaded[0]!=null:loaded[0].free()
	loader.queue_free();report.failures=failed
	var file:=FileAccess.open(OUT+"/performance.json",FileAccess.WRITE);file.store_string(JSON.stringify(report,"  "));file.close()
	print("ROCK_BANK_BATCH_RESULT ",JSON.stringify(report));quit(1 if failed else 0)
